/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// GitOpsProjectSpec defines the desired state of GitOpsProject
type GitOpsProjectSpec struct {
	// The url to the gitops repository.
	URL string `json:"url"`
	// The branch of the gitops repository holding the declcd configuration.
	Branch string `json:"branch"`
	// The stage of the declcd configuration.
	Stage string `json:"stage"`
	// This defines how often decl will try to fetch changes from the gitops repository.
	PullIntervalSeconds int `json:"pullIntervalSeconds"`
	// This flag tells the controller to suspend subsequent executions, it does
	// not apply to already started executions.  Defaults to false.
	// +optional
	Suspend *bool `json:"suspend,omitempty"`
}

// GitOpsProjectStatus defines the observed state of GitOpsProject
type GitOpsProjectStatus struct {
	Conditions []metav1.Condition `json:"conditions,omitempty"`
}

// GitOpsProject is the Schema for the gitopsprojects API
type GitOpsProject struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   GitOpsProjectSpec   `json:"spec,omitempty"`
	Status GitOpsProjectStatus `json:"status,omitempty"`
}

// GitOpsProjectList contains a list of GitOpsProject
type GitOpsProjectList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []GitOpsProject `json:"items"`
}

func init() {
	SchemeBuilder.Register(&GitOpsProject{}, &GitOpsProjectList{})
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitOpsProject) DeepCopyInto(out *GitOpsProject) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitOpsProject.
func (in *GitOpsProject) DeepCopy() *GitOpsProject {
	if in == nil {
		return nil
	}
	out := new(GitOpsProject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GitOpsProject) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitOpsProjectList) DeepCopyInto(out *GitOpsProjectList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GitOpsProject, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitOpsProjectList.
func (in *GitOpsProjectList) DeepCopy() *GitOpsProjectList {
	if in == nil {
		return nil
	}
	out := new(GitOpsProjectList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GitOpsProjectList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitOpsProjectSpec) DeepCopyInto(out *GitOpsProjectSpec) {
	*out = *in
	if in.Suspend != nil {
		in, out := &in.Suspend, &out.Suspend
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitOpsProjectSpec.
func (in *GitOpsProjectSpec) DeepCopy() *GitOpsProjectSpec {
	if in == nil {
		return nil
	}
	out := new(GitOpsProjectSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitOpsProjectStatus) DeepCopyInto(out *GitOpsProjectStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitOpsProjectStatus.
func (in *GitOpsProjectStatus) DeepCopy() *GitOpsProjectStatus {
	if in == nil {
		return nil
	}
	out := new(GitOpsProjectStatus)
	in.DeepCopyInto(out)
	return out
}
